/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student_enrollment_system;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author Kane
 */
public class EnrollmentGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollmentGUI.class.getName());

    private void gotoPnlTable() {
    CardLayout cl = (CardLayout) parentPanel.getLayout();
    cl.show(parentPanel, "viewTableCard");
    }
    
    private void centerTableText() {
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();

        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    
    void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        EnrollmentDAO dao = new EnrollmentDAO();
        ResultSet rs = dao.getAllEnrollments();
        
        if (rs != null) {
            try {
                while (rs.next()) {
                    
                    String studentName = rs.getString("first_name") + " " + rs.getString("last_name");
                    
                    Object[] row = {
                        rs.getInt("enrollment_id"),
                        studentName,
                        rs.getString("course_name"),
                        rs.getDate("enrollment_date")
                    };
                    model.addRow(row);
                }
            } catch (java.sql.SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void populateComboBoxes() {
        studentComboBox.removeAllItems();
        courseComboBox.removeAllItems();

        StudentDAO studentDAO = new StudentDAO();
        List<Student> studentList = studentDAO.getAllStudents();
        
        if (studentList != null) {
            for (Student s : studentList) {
                String fullName = s.getFname()+ " " + s.getLname();
                // Add the ComboItem object instead of a String
                studentComboBox.addItem(new ComboItem(s.getStudentid(), fullName));
            }
        }
        
        // Populate Courses
        CourseDAO courseDAO = new CourseDAO();
        List<Course> courseList = courseDAO.getAllCourses();
        
        if (courseList != null) {
            for (Course c : courseList) {
                // Add the ComboItem object instead of a String
                courseComboBox.addItem(new ComboItem(c.getCourseid(), c.getCoursename()));
            }
        }
    }
    
    public EnrollmentGUI() {
        initComponents();
        refreshTable();
        centerTableText();
        populateComboBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addEnrollmentCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addnewStudentLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        addEnrollmentBtn = new javax.swing.JButton();
        delEnrollmentCard = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        delEnrollmentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enrollment Window");

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 75));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(60, 75));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        btnBack.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusPainted(false);
        btnBack.addActionListener(this::btnBackActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(btnBack, gridBagConstraints);

        jPanel1.add(jPanel6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(266, 75));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Enroll Student");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel3.add(jButton1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(266, 75));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 153, 153));
        jButton2.setText("View Enrollments");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 89, 26, 90);
        jPanel4.add(jButton2, gridBagConstraints);

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(266, 75));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jButton3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 153));
        jButton3.setText("Delete Enrollment");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel5.add(jButton3, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        parentPanel.setLayout(new java.awt.CardLayout());

        pnlTable.setBackground(new java.awt.Color(240, 244, 249));
        pnlTable.setPreferredSize(new java.awt.Dimension(746, 60));
        pnlTable.setLayout(new java.awt.BorderLayout());

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enrollment ID", "Student Name", "Course Name", "Enrollment Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        pnlTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        parentPanel.add(pnlTable, "viewTableCard");

        addEnrollmentCard.setBackground(new java.awt.Color(240, 244, 249));
        addEnrollmentCard.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(606, 357));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        addnewStudentLabel.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        addnewStudentLabel.setForeground(new java.awt.Color(153, 153, 153));
        addnewStudentLabel.setText("Add New Enrollment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 60, 0);
        jPanel2.add(addnewStudentLabel, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Select Student:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        studentComboBox.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel2.add(studentComboBox, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Select Course:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        courseComboBox.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel2.add(courseComboBox, gridBagConstraints);

        addEnrollmentBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        addEnrollmentBtn.setText("Add");
        addEnrollmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEnrollmentBtn.addActionListener(this::addEnrollmentBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(80, 0, 0, 0);
        jPanel2.add(addEnrollmentBtn, gridBagConstraints);

        addEnrollmentCard.add(jPanel2, new java.awt.GridBagConstraints());

        parentPanel.add(addEnrollmentCard, "addEnrollmentCard");

        delEnrollmentCard.setBackground(new java.awt.Color(240, 244, 249));
        delEnrollmentCard.setLayout(new java.awt.GridBagLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(606, 357));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Delete Enrollment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 120, 0);
        jPanel7.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Enrollment ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel7.add(jLabel7, gridBagConstraints);

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDragEnabled(true);
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel7.add(jTextField1, gridBagConstraints);

        delEnrollmentBtn.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        delEnrollmentBtn.setText("Delete ");
        delEnrollmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delEnrollmentBtn.setPreferredSize(new java.awt.Dimension(96, 23));
        delEnrollmentBtn.addActionListener(this::delEnrollmentBtnActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(120, 0, 0, 0);
        jPanel7.add(delEnrollmentBtn, gridBagConstraints);

        delEnrollmentCard.add(jPanel7, new java.awt.GridBagConstraints());

        parentPanel.add(delEnrollmentCard, "delEnrollmentCard");

        getContentPane().add(parentPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "addEnrollmentCard");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gotoPnlTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cl = (CardLayout) parentPanel.getLayout();
        cl.show(parentPanel, "delEnrollmentCard");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased

    }//GEN-LAST:event_jTable1MouseReleased

    private void addEnrollmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnrollmentBtnActionPerformed
        
    if (studentComboBox.getSelectedItem() == null || courseComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select both a student and a course.");
            return;
        }

        try {
            // Retrieve the selected ComboItem objects
            ComboItem selectedStudent = (ComboItem) studentComboBox.getSelectedItem();
            ComboItem selectedCourse = (ComboItem) courseComboBox.getSelectedItem();

            // Extract the hidden IDs
            int studentId = selectedStudent.getId();
            int courseId = selectedCourse.getId();

            // Add the enrollment using your DAO
            EnrollmentDAO dao = new EnrollmentDAO();
            dao.addEnrollment(studentId, courseId);

            JOptionPane.showMessageDialog(this, "Student enrolled successfully!");
            
            // Refresh the table and return to view
            refreshTable();
            gotoPnlTable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error processing enrollment.");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addEnrollmentBtnActionPerformed

    private void delEnrollmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delEnrollmentBtnActionPerformed
    
    String idStr = jTextField1.getText();
        
        if(idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Enrollment ID to delete.");
            return;
        }
        
        try {
            int enrollmentId = Integer.parseInt(idStr);
            EnrollmentDAO dao = new EnrollmentDAO();
            boolean isDeleted = dao.deleteEnrollment(enrollmentId);
            
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Enrollment deleted successfully!");
                jTextField1.setText("");
                refreshTable();
                gotoPnlTable(); 
            } else {
                JOptionPane.showMessageDialog(this, "Enrollment ID not found!");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID must be a valid number!");
        }    

    }//GEN-LAST:event_delEnrollmentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EnrollmentGUI().setVisible(true));
    }
    
    class ComboItem {
    private int id;
    private String label;

    public ComboItem(int id, String label) {
        this.id = id;
        this.label = label;
    }

    public int getId() {
        return id;
    }

    // This is the magic! The ComboBox will only show whatever this method returns.
    @Override
    public String toString() {
        return label; 
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnrollmentBtn;
    private javax.swing.JPanel addEnrollmentCard;
    private javax.swing.JLabel addnewStudentLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Object> courseComboBox;
    private javax.swing.JButton delEnrollmentBtn;
    private javax.swing.JPanel delEnrollmentCard;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JComboBox<Object> studentComboBox;
    // End of variables declaration//GEN-END:variables
}
